name: Move File

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

permissions:
  contents: write      

jobs:
  move_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}

      - name: Hello Step
        run: echo "Hello ${{ github.actor }}"

      - name: Move file
        run: |
          mkdir -p prueba
          cp archivo.txt prueba

      - name: Commit changes
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Move file"
          git push