name: Move File

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

permissions:
  contents: write      

jobs:
  move_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}

      - name: Hello Step
        run: echo "Hello ${{ github.actor }}"

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          #SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: 'cexposit'
          destination-repository-name: 'td2'
          user-email: cexposit@ull.edu.es
          target-branch: main
      
      
      
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source_file: 'archivo.txt'
          destination_repo: 'cexposit/td2'
          destination_folder: '.'
          user_email: 'cexposit@ull.edu.es'
          user_name: 'cexposit'
          commit_message: 'A custom message for the commit'          

      #- name: Clone target repository
        #run: |
          #git clone https://.:${{ secrets.GITHUB_TOKEN }}@github.com/kaizten/todelete2.git target
          #cp archivo.txt target/
          #cd target/
          #ls
          #git config --global user.email "cexposit@ull.edu.es"
          #git config --global user.name "cexposit"
          #git remote set-url origin https://cexposit:${{ secrets.GITHUB_TOKEN }}@github.com/kaizten/todelete2.git
          #git add .
          #git diff-index --quiet HEAD || git commit -m "Automatic publish from github.com/project"
          #git push

      #- name: Checkout target repository
      #  uses: actions/checkout@v3
      #  with:
      #    repository: kaizten/todelete2
      #    ref: main
#     #     token: ${{ secrets.TARGET_REPOSITORY_TOKEN }}

      #- name: Move file
      #  run: |
      #    mkdir -p prueba
      #    cp archivo.txt prueba
        
      #- name: Commit changes
      #  run: |
      #    git config --global user.email "cexposit@ull.edu.es"
      #    git config --global user.name "cexposit"
      #    git add .
      #    git commit -m "Move file"
      #    git push
