name: Clone and Push

on:
  push:
    branches: [ main ]

jobs:
  clone_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- name: creates output
        #run:  sh ./build.sh # some command from your repository that creates
        #                    # output to "source-directory" ("output" in the example)
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: 'cexposit'
          destination-repository-name: 'td2'
          user-email: carles3@pina.cat
          target-branch: main